### ISSUE TITLE
Define the basic layout of the main page before logging in

### ISSUE THREAD

**Issue by dor4231** [PositiveYou/NetHood#8]
Open for discussion.

@YoadElkayam @moshedidi @YoavBZ @

How will the user interact with the app the first time he opens the website

**Comment by YoavBZ** [comment]
I'm thinking about some kind of a walkthrough.
Check this out:
https://www.npmjs.com/package/reactour

**Comment by moshedidi** [comment]
I agree with Yoav, there should be a mandatory step by step guild that has 2 main goals,
1. The user will build his base profile(FB login, any other details that we want)
2. The user will be introduced to the main screens and features of the app.
@YoavBZ not sure that specific example as it seems a bit bumpy, maybe something like: https://github.com/heinrichreimer/material-intro/blob/master/README.md
That goes page by page?

**Comment by YoadElkayam** [comment]
working on it

בתאריך יום ב׳, 17 בספט׳ 2018, 09:37, מאת Moshe Didi ‏<
notifications@github.com>:

**Comment by YoavBZ** [comment]
@moshedidi
Well that can be a solution for the React web app.
In case of an Android app, I totally agree with you (I actually tried the library you sent few weeks ago and really recommend it)

**Comment by dor4231** [comment]
@YoadElkayam is working on a design using Photoshop.

As we discussed today, the login/sign-up page should include:
- Google sign-in.
- Facebook sign-in.
- Nethood sign-in.
- Some pictures related to sports.
- A glance at the application after login.
- No devices - just snapshots from the full app in both **Desktop** and **Mobile** versions.
- Pictures captured by NetHood users.
- Pictures of non-athletes people doing sports.
- Create a vibe of "Free Free Free Fun Fun Fun OUTSIDE!"

**Comment by dankons31** [comment]
Just a thought, what do you say that maybe we do something like the easy app (https://easy.co.il/en/)
Before even giving any info about her/himself (the user) can search any sports events occurring around him or in the desired location. And after viewing our awesome platform and choosing an event the user needs to provide sign-up info. Because think about it as a user that sees this for the first time, I want to know what's inside before I log in with my FB account or whatever, first let me see what you offer then I will trust you and give you access to my info. We are thinking from a point of view of knowing how awesome the platform is and what it is providing but the user is clueless and nowadays everyone is suspicious.

**Comment by dankons31** [comment]
mischief managed
